const SUCCESS_CODE = 200;
const CREATED_CODE = 201;

const BAD_REQUEST_ERROR = 400;
const UNAUTHORIZED_ERROR = 401;
const FORBIDDEN_ERROR = 403;
const NOT_FOUND_ERROR = 404;
const CONFLICT_ERROR = 409;
const DEFAULT_SERVER_ERROR = 500;

const DUPLICATE_KEY_ERROR = 11000;

module.exports = {
  SUCCESS_CODE,
  CREATED_CODE,
  BAD_REQUEST_ERROR,
  UNAUTHORIZED_ERROR,
  FORBIDDEN_ERROR,
  NOT_FOUND_ERROR,
  CONFLICT_ERROR,
  DEFAULT_SERVER_ERROR,
  DUPLICATE_KEY_ERROR,
};
